# Generated by Django 4.2.5 on 2023-09-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproducto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Producto', 'verbose_name_plural': 'historical Productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='historicalcategoriaproducto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.categoriaproducto', verbose_name='Categoria del producto'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoriaproducto', verbose_name='Categoria del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
