# Generated by Django 4.2.5 on 2023-09-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='es_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='es_activo',
            new_name='is_active',
        ),
    ]
