# Generated by Django 4.2.5 on 2023-09-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='es_personal',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='es_personal',
            new_name='is_staff',
        ),
    ]
